baseURL: "https://jirureta.github.io" 
title: Jon Irureta
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Talks
          url: data/
          weight: 4

params:
    description: "This website hosts Jon Irureta Barrena's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Jon Irureta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jon Irureta
          subtitle: "I am a Professor in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Talks
              url: data/
            - name: News
              url: books/
    socialIcons:
        - name: CV
          url: CV.pdf
        - name: Email
          url: mailto:jirureta@ikerlan.es
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Ev3aiKQAAAAJ&hl=es
        - name: GitHub
          url: https://github.com/JIrureta
        - name: LinkedIn
          url: https://www.linkedin.com/in/jon-irureta-barrena-b433901b3/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jon Irureta"
      icon: flavicon.png
      iconHeight: 24

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
